.TH "MLX42/src Directory Reference" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLX42/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBfont\fP"
.br
.ti -1c
.RI "directory \fBtextures\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmlx_cursor\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_exit\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_images\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_init\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_keys\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_loop\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_monitor\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_mouse\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_put_pixel\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_window\&.c\fP"
.br
.in -1c
