.TH "MLX42/src/utils Directory Reference" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLX42/src/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmlx_compare\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_error\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_list\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_utils\&.c\fP"
.br
.in -1c
