.TH "MLX42/include Directory Reference" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLX42/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBglad\fP"
.br
.ti -1c
.RI "directory \fBKHR\fP"
.br
.ti -1c
.RI "directory \fBlodepng\fP"
.br
.ti -1c
.RI "directory \fBMLX42\fP"
.br
.in -1c
