.TH "MLX42/src/textures Directory Reference" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLX42/src/textures Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmlx_png\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_texture\&.c\fP"
.br
.ti -1c
.RI "file \fBmlx_xpm42\&.c\fP"
.br
.in -1c
