.TH "/home/dev/frfr Directory Reference" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/frfr Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBlatex\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcalcs\&.c\fP"
.br
.RI "Core calculation functions for the fractal rendering\&. "
.ti -1c
.RI "file \fBfractol\&.h\fP"
.br
.RI "Header file for the Fractol project, containing all declarations, enumerations, structures, and function prototypes used in the fractal rendering application\&. "
.ti -1c
.RI "file \fBjulia\&.c\fP"
.br
.RI "Julia set rendering logic for the Fractol project\&. "
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Entry point for the Fractol application\&. "
.ti -1c
.RI "file \fBMakefile\fP"
.br
.ti -1c
.RI "file \fBmandelbrot\&.c\fP"
.br
.RI "Mandelbrot set rendering logic for the Fractol project\&. "
.ti -1c
.RI "file \fButils\&.c\fP"
.br
.RI "Utility functions for the Fractol project\&. "
.in -1c
