.TH "MLX42/src/font/font.h" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLX42/src/font/font.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_font\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBFONT_WIDTH\fP   10"
.br
.ti -1c
.RI "#\fBdefine\fP \fBFONT_HEIGHT\fP   20"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBstruct\fP \fBs_font\fP \fBfont_atlas\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP FONT_HEIGHT   20"

.PP
Definition at line \fB16\fP of file \fBfont\&.h\fP\&.
.SS "#\fBdefine\fP FONT_WIDTH   10"

.PP
Definition at line \fB15\fP of file \fBfont\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBstruct\fP \fBs_font\fP font_atlas\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
