.TH "gladGLversionStruct" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gladGLversionStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glad\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmajor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBminor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB50\fP of file \fBglad\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBint\fP gladGLversionStruct::major"

.PP
Definition at line \fB51\fP of file \fBglad\&.h\fP\&.
.SS "\fBint\fP gladGLversionStruct::minor"

.PP
Definition at line \fB52\fP of file \fBglad\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
