.TH "LodePNGEncoderSettings" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LodePNGEncoderSettings
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lodepng\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLodePNGCompressSettings\fP \fBzlibsettings\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBauto_convert\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBfilter_palette_zero\fP"
.br
.ti -1c
.RI "\fBLodePNGFilterStrategy\fP \fBfilter_strategy\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP \fBchar\fP * \fBpredefined_filters\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBforce_palette\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBadd_id\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBtext_compression\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB818\fP of file \fBlodepng\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBunsigned\fP LodePNGEncoderSettings::add_id"

.PP
Definition at line \fB846\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGEncoderSettings::auto_convert"

.PP
Definition at line \fB821\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGEncoderSettings::filter_palette_zero"

.PP
Definition at line \fB827\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBLodePNGFilterStrategy\fP LodePNGEncoderSettings::filter_strategy"

.PP
Definition at line \fB830\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGEncoderSettings::force_palette"

.PP
Definition at line \fB843\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBconst\fP \fBunsigned\fP \fBchar\fP* LodePNGEncoderSettings::predefined_filters"

.PP
Definition at line \fB835\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGEncoderSettings::text_compression"

.PP
Definition at line \fB848\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBLodePNGCompressSettings\fP LodePNGEncoderSettings::zlibsettings"

.PP
Definition at line \fB819\fP of file \fBlodepng\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
