.TH "LodePNGState" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LodePNGState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lodepng\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLodePNGDecoderSettings\fP \fBdecoder\fP"
.br
.ti -1c
.RI "\fBLodePNGEncoderSettings\fP \fBencoder\fP"
.br
.ti -1c
.RI "\fBLodePNGColorMode\fP \fBinfo_raw\fP"
.br
.ti -1c
.RI "\fBLodePNGInfo\fP \fBinfo_png\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB858\fP of file \fBlodepng\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBLodePNGDecoderSettings\fP LodePNGState::decoder"

.PP
Definition at line \fB860\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBLodePNGEncoderSettings\fP LodePNGState::encoder"

.PP
Definition at line \fB863\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGState::error"

.PP
Definition at line \fB867\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBLodePNGInfo\fP LodePNGState::info_png"

.PP
Definition at line \fB866\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBLodePNGColorMode\fP LodePNGState::info_raw"

.PP
Definition at line \fB865\fP of file \fBlodepng\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
