.TH "LodePNGTime" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LodePNGTime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lodepng\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBunsigned\fP \fByear\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBmonth\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBday\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBhour\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBminute\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBsecond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB466\fP of file \fBlodepng\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBunsigned\fP LodePNGTime::day"

.PP
Definition at line \fB469\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGTime::hour"

.PP
Definition at line \fB470\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGTime::minute"

.PP
Definition at line \fB471\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGTime::month"

.PP
Definition at line \fB468\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGTime::second"

.PP
Definition at line \fB472\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGTime::year"

.PP
Definition at line \fB467\fP of file \fBlodepng\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
