.TH "LodePNGColorMode" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LodePNGColorMode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lodepng\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLodePNGColorType\fP \fBcolortype\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBbitdepth\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBchar\fP * \fBpalette\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBpalettesize\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBkey_defined\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBkey_r\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBkey_g\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBkey_b\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB384\fP of file \fBlodepng\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBunsigned\fP LodePNGColorMode::bitdepth"

.PP
Definition at line \fB387\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBLodePNGColorType\fP LodePNGColorMode::colortype"

.PP
Definition at line \fB386\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorMode::key_b"

.PP
Definition at line \fB423\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorMode::key_defined"

.PP
Definition at line \fB420\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorMode::key_g"

.PP
Definition at line \fB422\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorMode::key_r"

.PP
Definition at line \fB421\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP \fBchar\fP* LodePNGColorMode::palette"

.PP
Definition at line \fB406\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBsize_t\fP LodePNGColorMode::palettesize"

.PP
Definition at line \fB407\fP of file \fBlodepng\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
