.TH "LodePNGColorStats" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LodePNGColorStats
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lodepng\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBunsigned\fP \fBcolored\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBshort\fP \fBkey_r\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBshort\fP \fBkey_g\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBshort\fP \fBkey_b\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBalpha\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBnumcolors\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBchar\fP \fBpalette\fP [1024]"
.br
.ti -1c
.RI "\fBunsigned\fP \fBbits\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBnumpixels\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBallow_palette\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBallow_greyscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB792\fP of file \fBlodepng\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBunsigned\fP LodePNGColorStats::allow_greyscale"

.PP
Definition at line \fB806\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorStats::allow_palette"

.PP
Definition at line \fB805\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorStats::alpha"

.PP
Definition at line \fB798\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorStats::bits"

.PP
Definition at line \fB801\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorStats::colored"

.PP
Definition at line \fB793\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorStats::key"

.PP
Definition at line \fB794\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP \fBshort\fP LodePNGColorStats::key_b"

.PP
Definition at line \fB797\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP \fBshort\fP LodePNGColorStats::key_g"

.PP
Definition at line \fB796\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP \fBshort\fP LodePNGColorStats::key_r"

.PP
Definition at line \fB795\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGColorStats::numcolors"

.PP
Definition at line \fB799\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBsize_t\fP LodePNGColorStats::numpixels"

.PP
Definition at line \fB802\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP \fBchar\fP LodePNGColorStats::palette[1024]"

.PP
Definition at line \fB800\fP of file \fBlodepng\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
