.TH "LodePNGDecoderSettings" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LodePNGDecoderSettings
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lodepng\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBLodePNGDecompressSettings\fP \fBzlibsettings\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBignore_crc\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBignore_critical\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBignore_end\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBcolor_convert\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBread_text_chunks\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBremember_unknown_chunks\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBmax_text_size\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBmax_icc_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB730\fP of file \fBlodepng\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBunsigned\fP LodePNGDecoderSettings::color_convert"

.PP
Definition at line \fB742\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGDecoderSettings::ignore_crc"

.PP
Definition at line \fB734\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGDecoderSettings::ignore_critical"

.PP
Definition at line \fB735\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGDecoderSettings::ignore_end"

.PP
Definition at line \fB736\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBsize_t\fP LodePNGDecoderSettings::max_icc_size"

.PP
Definition at line \fB758\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBsize_t\fP LodePNGDecoderSettings::max_text_size"

.PP
Definition at line \fB753\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGDecoderSettings::read_text_chunks"

.PP
Definition at line \fB745\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBunsigned\fP LodePNGDecoderSettings::remember_unknown_chunks"

.PP
Definition at line \fB748\fP of file \fBlodepng\&.h\fP\&.
.SS "\fBLodePNGDecompressSettings\fP LodePNGDecoderSettings::zlibsettings"

.PP
Definition at line \fB731\fP of file \fBlodepng\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
