.TH "md_MLX42_2CONTRIBUTING" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_MLX42_2CONTRIBUTING \- How to contribute to MLX42 
.PP
 
.SH "Read the wiki for repo codestyle!"
.PP
For any questions, suggestions or help \fCContact Me\fP
.SH "<strong>Found a bug?</strong>"
.PP
.IP "\(bu" 2
Avoid opening any new issues without having checked if your problem has already been reported\&. If there are no currently open issues that fit your problem's description, feel free to \fCadd it\fP\&.
.IP "\(bu" 2
When writing an issue make sure to include a clear title and description as well as having filled out all the necessary information: System info, OS, OS-Version, \&.\&.\&.
.IP "\(bu" 2
If possible add pictures of the issue\&.
.IP "\(bu" 2
Maybe fix it yourself :D ?
.PP
.SH "Contributing"
.PP
Before thinking of adding a contribution, think\&. Is it necessary? Will this actually be a useful/required feature? Is your implementation good? Provide clear and documented explanation as to what was changed\&. 
