.TH "md_MLX42_2SECURITY" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_MLX42_2SECURITY \- Security Policy 
.PP
 
.SH "Supported Versions"
.PP
Version   Supported    2\&.x\&.x   ✅    1\&.0\&.x   ❌   
.SH "Reporting a Vulnerability"
.PP
For security issues please refrain from opening an issue! Instead write an email to \fCmain@w2wizard\&.dev\fP 
