.TH "mlx" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlx
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MLX42\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBwindow\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBcontext\fP"
.br
.ti -1c
.RI "\fBint32_t\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint32_t\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBdouble\fP \fBdelta_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main MLX handle, carries important data in regards to the program\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP The window itself\&. 
.br
\fIcontext\fP Abstracted opengl data\&. 
.br
\fIwidth\fP The width of the window\&. 
.br
\fIheight\fP The height of the window\&. 
.br
\fIdelta_time\fP The time difference between the previous frame and the current frame\&. 
.RE
.PP

.PP
Definition at line \fB360\fP of file \fBMLX42\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBvoid\fP* mlx::context"

.PP
Definition at line \fB363\fP of file \fBMLX42\&.h\fP\&.
.SS "\fBdouble\fP mlx::delta_time"

.PP
Definition at line \fB366\fP of file \fBMLX42\&.h\fP\&.
.SS "\fBint32_t\fP mlx::height"

.PP
Definition at line \fB365\fP of file \fBMLX42\&.h\fP\&.
.SS "\fBint32_t\fP mlx::width"

.PP
Definition at line \fB364\fP of file \fBMLX42\&.h\fP\&.
.SS "\fBvoid\fP* mlx::window"

.PP
Definition at line \fB362\fP of file \fBMLX42\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
