.TH "mlx_cursor" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlx_cursor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MLX42_Int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBparam\fP"
.br
.ti -1c
.RI "\fBmlx_cursorfunc\fP \fBfunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB126\fP of file \fBMLX42_Int\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBmlx_cursorfunc\fP mlx_cursor::func"

.PP
Definition at line \fB129\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBvoid\fP* mlx_cursor::param"

.PP
Definition at line \fB128\fP of file \fBMLX42_Int\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
