.TH "mlx_image_ctx" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlx_image_ctx
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MLX42_Int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGLuint\fP \fBtexture\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBinstances_capacity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB206\fP of file \fBMLX42_Int\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBsize_t\fP mlx_image_ctx::instances_capacity"

.PP
Definition at line \fB209\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBGLuint\fP mlx_image_ctx::texture"

.PP
Definition at line \fB208\fP of file \fBMLX42_Int\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
