.TH "mlx_resize" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlx_resize
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MLX42_Int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBparam\fP"
.br
.ti -1c
.RI "\fBmlx_resizefunc\fP \fBfunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB138\fP of file \fBMLX42_Int\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBmlx_resizefunc\fP mlx_resize::func"

.PP
Definition at line \fB141\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBvoid\fP* mlx_resize::param"

.PP
Definition at line \fB140\fP of file \fBMLX42_Int\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
