.TH "mlx_key" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlx_key
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MLX42_Int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBparam\fP"
.br
.ti -1c
.RI "\fBmlx_keyfunc\fP \fBfunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB144\fP of file \fBMLX42_Int\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBmlx_keyfunc\fP mlx_key::func"

.PP
Definition at line \fB147\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBvoid\fP* mlx_key::param"

.PP
Definition at line \fB146\fP of file \fBMLX42_Int\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
