.TH "s_atod_data" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_atod_data \- Helper structure for string-to-double conversion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fractol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBsign\fP"
.br
.ti -1c
.RI "double \fBresult\fP"
.br
.ti -1c
.RI "double \fBdivisor\fP"
.br
.ti -1c
.RI "double \fBfraction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper structure for string-to-double conversion\&. 
.PP
Definition at line \fB121\fP of file \fBfractol\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "double s_atod_data::divisor"

.PP
Definition at line \fB126\fP of file \fBfractol\&.h\fP\&.
.SS "double s_atod_data::fraction"

.PP
Definition at line \fB127\fP of file \fBfractol\&.h\fP\&.
.SS "int s_atod_data::i"

.PP
Definition at line \fB123\fP of file \fBfractol\&.h\fP\&.
.SS "double s_atod_data::result"

.PP
Definition at line \fB125\fP of file \fBfractol\&.h\fP\&.
.SS "int s_atod_data::sign"

.PP
Definition at line \fB124\fP of file \fBfractol\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
