.TH "s_color" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_color \- Represents an RGB color\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fractol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBg\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an RGB color\&. 
.PP
Definition at line \fB81\fP of file \fBfractol\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int s_color::b"

.PP
Definition at line \fB85\fP of file \fBfractol\&.h\fP\&.
.SS "int s_color::g"

.PP
Definition at line \fB84\fP of file \fBfractol\&.h\fP\&.
.SS "int s_color::r"

.PP
Definition at line \fB83\fP of file \fBfractol\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
