.TH "s_data" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_data \- Data structure for fractal rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fractol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBzoom\fP"
.br
.ti -1c
.RI "double \fBc\fP [2]"
.br
.ti -1c
.RI "double \fBoffset\fP [2]"
.br
.ti -1c
.RI "mlx_t * \fBmlx\fP"
.br
.ti -1c
.RI "mlx_image_t * \fBimg\fP"
.br
.ti -1c
.RI "\fBt_fractal_type\fP \fBfractal_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure for fractal rendering\&. 
.PP
Definition at line \fB91\fP of file \fBfractol\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "double s_data::c[2]"

.PP
Definition at line \fB94\fP of file \fBfractol\&.h\fP\&.
.SS "\fBt_fractal_type\fP s_data::fractal_type"

.PP
Definition at line \fB98\fP of file \fBfractol\&.h\fP\&.
.SS "mlx_image_t* s_data::img"

.PP
Definition at line \fB97\fP of file \fBfractol\&.h\fP\&.
.SS "mlx_t* s_data::mlx"

.PP
Definition at line \fB96\fP of file \fBfractol\&.h\fP\&.
.SS "double s_data::offset[2]"

.PP
Definition at line \fB95\fP of file \fBfractol\&.h\fP\&.
.SS "double s_data::zoom"

.PP
Definition at line \fB93\fP of file \fBfractol\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
