.TH "s_render_vars" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_render_vars \- Variables used for fractal rendering calculations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fractol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBiterations\fP"
.br
.ti -1c
.RI "double \fBscale\fP [2]"
.br
.ti -1c
.RI "double \fBstart\fP [2]"
.br
.ti -1c
.RI "double \fBz\fP [2]"
.br
.ti -1c
.RI "double \fBz_squared\fP [2]"
.br
.ti -1c
.RI "double \fBc_re\fP [2]"
.br
.ti -1c
.RI "double \fBc_re_centered\fP"
.br
.ti -1c
.RI "double \fBc_im\fP"
.br
.ti -1c
.RI "uint32_t * \fBpixels\fP"
.br
.ti -1c
.RI "uint32_t * \fBrow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Variables used for fractal rendering calculations\&. 
.PP
Definition at line \fB104\fP of file \fBfractol\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "double s_render_vars::c_im"

.PP
Definition at line \fB113\fP of file \fBfractol\&.h\fP\&.
.SS "double s_render_vars::c_re[2]"

.PP
Definition at line \fB111\fP of file \fBfractol\&.h\fP\&.
.SS "double s_render_vars::c_re_centered"

.PP
Definition at line \fB112\fP of file \fBfractol\&.h\fP\&.
.SS "int s_render_vars::iterations"

.PP
Definition at line \fB106\fP of file \fBfractol\&.h\fP\&.
.SS "uint32_t* s_render_vars::pixels"

.PP
Definition at line \fB114\fP of file \fBfractol\&.h\fP\&.
.SS "uint32_t* s_render_vars::row"

.PP
Definition at line \fB115\fP of file \fBfractol\&.h\fP\&.
.SS "double s_render_vars::scale[2]"

.PP
Definition at line \fB107\fP of file \fBfractol\&.h\fP\&.
.SS "double s_render_vars::start[2]"

.PP
Definition at line \fB108\fP of file \fBfractol\&.h\fP\&.
.SS "double s_render_vars::z[2]"

.PP
Definition at line \fB109\fP of file \fBfractol\&.h\fP\&.
.SS "double s_render_vars::z_squared[2]"

.PP
Definition at line \fB110\fP of file \fBfractol\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
