.TH "ucvector" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ucvector
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBunsigned\fP \fBchar\fP * \fBdata\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBallocsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB262\fP of file \fBlodepng\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBsize_t\fP ucvector::allocsize"

.PP
Definition at line \fB265\fP of file \fBlodepng\&.c\fP\&.
.SS "\fBunsigned\fP \fBchar\fP* ucvector::data"

.PP
Definition at line \fB263\fP of file \fBlodepng\&.c\fP\&.
.SS "\fBsize_t\fP ucvector::size"

.PP
Definition at line \fB264\fP of file \fBlodepng\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
