.TH "vertex" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MLX42_Int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfloat\fP \fBx\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBy\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBz\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBu\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBv\fP"
.br
.ti -1c
.RI "\fBint8_t\fP \fBtex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB74\fP of file \fBMLX42_Int\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBint8_t\fP vertex::tex"

.PP
Definition at line \fB81\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBfloat\fP vertex::u"

.PP
Definition at line \fB79\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBfloat\fP vertex::v"

.PP
Definition at line \fB80\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBfloat\fP vertex::x"

.PP
Definition at line \fB76\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBfloat\fP vertex::y"

.PP
Definition at line \fB77\fP of file \fBMLX42_Int\&.h\fP\&.
.SS "\fBfloat\fP vertex::z"

.PP
Definition at line \fB78\fP of file \fBMLX42_Int\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
