.TH "xpm" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MLX42\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmlx_texture_t\fP \fBtexture\fP"
.br
.ti -1c
.RI "\fBint32_t\fP \fBcolor_count\fP"
.br
.ti -1c
.RI "\fBint32_t\fP \fBcpp\fP"
.br
.ti -1c
.RI "\fBchar\fP \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct containing data regarding an XPM image\&.
.PP
\fBParameters\fP
.RS 4
\fItexture\fP The texture data of the XPM\&. 
.br
\fIcolor_count\fP The amount of colors available\&. 
.br
\fIcpp\fP The amount of characters per pixel\&. 
.br
\fImode\fP The color mode, either (c)olor or (m)onochrome\&. 
.RE
.PP

.PP
Definition at line \fB279\fP of file \fBMLX42\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBint32_t\fP xpm::color_count"

.PP
Definition at line \fB282\fP of file \fBMLX42\&.h\fP\&.
.SS "\fBint32_t\fP xpm::cpp"

.PP
Definition at line \fB283\fP of file \fBMLX42\&.h\fP\&.
.SS "\fBchar\fP xpm::mode"

.PP
Definition at line \fB284\fP of file \fBMLX42\&.h\fP\&.
.SS "\fBmlx_texture_t\fP xpm::texture"

.PP
Definition at line \fB281\fP of file \fBMLX42\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
