.TH "MLX42/tools/xpm3_conv.py" 3 "Version 1.0" "Fractol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLX42/tools/xpm3_conv.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpm3_conv\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxpm3_conv\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdict\fP \fBxpm3_conv\&.colours\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fractol from the source code\&.
