var searchData=
[
  ['¿cómo_20funciona_0',['3.2 ¿Cómo funciona?',['../md_main__explained.html#autotoc_md106',1,'']]],
  ['¿por_20qué_20es_20útil_1',['¿por qué es útil',['../md_auxiliary__explained.html#autotoc_md8',1,'¿Por qué es útil?'],['../md_auxiliary__explained.html#autotoc_md16',1,'¿Por qué es útil?'],['../md_auxiliary__explained.html#autotoc_md24',1,'¿Por qué es útil?'],['../md_auxiliary__explained.html#autotoc_md32',1,'¿Por qué es útil?']]],
  ['¿por_20qué_20es_20importante_2',['¿por qué es importante',['../md_main__explained.html#autotoc_md126',1,'¿Por qué es importante?'],['../md_main__explained.html#autotoc_md169',1,'¿Por qué es importante?'],['../md_main__explained.html#autotoc_md163',1,'¿Por qué es importante?'],['../md_main__explained.html#autotoc_md157',1,'¿Por qué es importante?'],['../md_main__explained.html#autotoc_md148',1,'¿Por qué es importante?'],['../md_main__explained.html#autotoc_md132',1,'¿Por qué es importante?'],['../md_main__explained.html#autotoc_md129',1,'¿Por qué es importante?'],['../md_main__explained.html#autotoc_md123',1,'¿Por qué es importante?']]],
  ['¿qué_20debe_20recordar_20un_20desarrollador_3',['5.1.6 ¿Qué debe recordar un desarrollador?',['../md_main__explained.html#autotoc_md134',1,'']]],
  ['¿qué_20hace_4',['¿qué hace',['../md_main__explained.html#autotoc_md161',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md152',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md122',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md143',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md125',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md167',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md128',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md131',1,'¿Qué hace?'],['../md_main__explained.html#autotoc_md110',1,'4.1 ¿Qué hace?']]],
  ['¿qué_20hace_20c_5',['¿Qué hace c?',['../md_main__explained.html#autotoc_md101',1,'']]],
  ['¿qué_20hace_20esta_20función_6',['¿qué hace esta función',['../md_auxiliary__explained.html#autotoc_md11',1,'¿Qué hace esta función?'],['../md_mandelbrot__calcs.html#autotoc_md175',1,'¿Qué hace esta función?'],['../md_mandelbrot__calcs.html#autotoc_md181',1,'¿Qué hace esta función?'],['../md_mandelbrot__calcs.html#autotoc_md187',1,'¿Qué hace esta función?'],['../md_auxiliary__explained.html#autotoc_md19',1,'¿Qué hace esta función?'],['../md_mandelbrot__calcs.html#autotoc_md192',1,'¿Qué hace esta función?'],['../md_mandelbrot__calcs.html#autotoc_md197',1,'¿Qué hace esta función?'],['../md_auxiliary__explained.html#autotoc_md27',1,'¿Qué hace esta función?'],['../md_auxiliary__explained.html#autotoc_md35',1,'¿Qué hace esta función?'],['../md_main__explained.html#autotoc_md137',1,'¿Qué hace esta función?'],['../md_julia__calcs.html#autotoc_md56',1,'¿Qué hace esta función?'],['../md_julia__calcs.html#autotoc_md67',1,'¿Qué hace esta función?'],['../md_auxiliary__explained.html#autotoc_md3',1,'¿Qué hace esta función?'],['../md_julia__calcs.html#autotoc_md80',1,'¿Qué hace esta función?'],['../md_main__explained.html#autotoc_md104',1,'3.1 ¿Qué hace esta función?']]],
  ['¿qué_20pasa_20si_20hay_20un_20error_7',['3.3 ¿Qué pasa si hay un error?',['../md_main__explained.html#autotoc_md107',1,'']]]
];
